### ISSUE TITLE
Update the holopin.yaml to use the website badge

### ISSUE THREAD

**Issue by marcduiker** [dapr/website#92]
Update the `.github/holopin.yaml` file with the following info to set the default [Holopin badge](https://www.holopin.io/sticker/clrqffunr242860gjxng34gcru) for this repo:

```yaml
organization: dapr
defaultSticker: clrqffunr242860gjxng34gcru
stickers:
  -
    id: clrqffunr242860gjxng34gcru
    alias: website-badge
```

Once this is in place, maintainers can award contributors via the Holopin Bot by mentioning the contributors' username in a PR comment when the PR is accepted: `@holopin-bot @username`
